[package]
name = "green-tea-v1"
description = "Green threads on x86_64, first version: one global scheduler context."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
publish.workspace = true

[dependencies]
libc = "1.0.0-alpha.4"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
test-log = { version = "0.2.21" , features = ["trace"]}
